[tools]
# Language and runtimes
"core:python" = "3.13.14"

# Package management
"aqua:astral-sh/uv" = "0.11"

# Version management
"aqua:crate-ci/committed"      = "1.1.11"
"aqua:j178/prek"               = "0.4.11"
"aqua:betterleaks/betterleaks" = "1.7.3"

# General CLI tools
"aqua:casey/just" = "1.57.0"

# Language tooling
"aqua:astral-sh/ruff"   = "0.16.1"
"aqua:biomejs/biome"    = "2.5.6"
"aqua:crate-ci/typos"   = "1.48.0"
"pipx:pyrefly"          = "1.2.0"
"aqua:tombi-toml/tombi" = "1.2.5"
"aqua:vale-cli/vale"    = "3.17.0"
"github:rvben/rumdl"    = "v0.2.48"

[settings]
experimental = true

  [settings.python]
  uv_venv_auto = "create|source"
