[default.extend-words]
hald        = "hald"
spektrafilm = "spektrafilm"
portra      = "portra"
endura      = "endura"
ektacolor   = "ektacolor"
fujifilm    = "fujifilm"
napari      = "napari"
darktable   = "darktable"
vulkan      = "vulkan"
vkdt        = "vkdt"
luts        = "luts"
halated     = "halated"
upscaling   = "upscaling"
unsharp     = "unsharp"
unmixing    = "unmixing"
tooltip     = "tooltip"
tooltips    = "tooltips"
datasheet   = "datasheet"
datasheets  = "datasheets"
subreddit   = "subreddit"
github      = "github"

[default.extend-identifiers]
Portra    = "Portra"
Endura    = "Endura"
Ektacolor = "Ektacolor"
Fujifilm  = "Fujifilm"
Vulkan    = "Vulkan"
LUTs      = "LUTs"
GitHub    = "GitHub"
