from __future__ import annotations

GRAY_0 = '#7f7f7f'
GRAY_1 = '#858585'
GRAY_2 = '#8a8a8a'
GRAY_3 = '#909090'
TEXT_DIM = '#ececec'
TEXT_MAIN = '#ffffff'
TEXT_BOLD = '#ffffff'

FONT_SIZE_BASE = '12pt'
FONT_SIZE_TAB = '9pt'

FONT_WEIGHT_SEMIBOLD = 600
FONT_WEIGHT_BOLD = 700

SIZE_TAB_STRIP_OFFSET = '0px'
SIZE_TAB_PADDING = '4px 8px'
SIZE_TAB_MARGIN_RIGHT = '4px'
SIZE_CONTROL_MIN_HEIGHT = '18px'
SIZE_CONTROL_PADDING = '2px 4px'
SIZE_BUTTON_MIN_HEIGHT = '30px'
SIZE_BUTTON_PADDING = '0px 6px'
SIZE_COMBO_DROPDOWN_WIDTH = '14px'
SIZE_SPIN_BUTTON_WIDTH = '12px'
SIZE_HEADER_PADDING = '2px 6px'
SIZE_CHECKBOX_SPACING = '6px'
SIZE_CHECKBOX_INDICATOR = '14px'
SIZE_TOOLBUTTON_PADDING = '2px 4px'
SIZE_TOOLBUTTON_POPUP_PADDING_RIGHT = '2px'
SIZE_FORM_SPACING = '4px'
SIZE_SPLITTER_HANDLE_WIDTH = '4px'
SIZE_SCROLLBAR_HANDLE_MIN = '24px'

BASE_BG = GRAY_0
PANEL_BG = GRAY_0
PANEL_BG_ACTIVE = GRAY_1
TAB_SELECTED_BG = GRAY_2
CONTROL_BG = GRAY_2
CONTROL_BG_HOVER = GRAY_2
CONTROL_BG_PRESSED = GRAY_1
CONTROL_MENU_BG = GRAY_2
CONTROL_SELECTION_BG = GRAY_3
HEADER_BG = GRAY_1
CHECKED_BG = GRAY_3
DISABLED_BG = GRAY_1
SCROLLBAR_HANDLE_BG = GRAY_3
SPLITTER_BG = GRAY_1
STATUS_BG = GRAY_2
TEXT_PRIMARY = TEXT_MAIN
TEXT_SOFT = TEXT_DIM
TEXT_BRIGHT = TEXT_BOLD
TEXT_HEADER = TEXT_MAIN
TEXT_CONTROL = TEXT_MAIN
TEXT_HEADER_SECTION = TEXT_DIM
TEXT_STATUS = TEXT_MAIN